# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasterClass',
            fields=[
                ('name', models.CharField(choices=[('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('cantrip', 'cantrip'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th')], max_length=255)),
                ('school', models.CharField(choices=[('Abjuration', 'Abjuration'), ('Conjuration', 'Conjuration'), ('Divination', 'Divination'), ('Enchantment', 'Enchantment'), ('Evocation', 'Evocation'), ('Illusion', 'Illusion'), ('Necromancy', 'Necromancy'), ('Transmutation', 'Transmutation')], max_length=255)),
                ('casting_time', models.CharField(max_length=255)),
                ('range', models.CharField(max_length=255)),
                ('components', models.CharField(max_length=2048)),
                ('duration', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('classes', models.ManyToManyField(to='spells.CasterClass')),
            ],
        ),
    ]
