# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_auto_20160407_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
