# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-25 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_spell_concentration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellSource',
            fields=[
                ('name', models.CharField(choices=[('phb', "Player's Handbook"), ('xge', "Xanathar's Guide to Everything")], max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='casterclass',
            name='name',
            field=models.CharField(choices=[('Artificer', 'Artificer'), ('Bard', 'Bard'), ('Cleric', 'Cleric'), ('Druid', 'Druid'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock'), ('Wizard', 'Wizard')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
