# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-07-25 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_auto_20180725_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.ForeignKey(default='phb', on_delete=django.db.models.deletion.CASCADE, to='spells.SpellSource'),
        ),
    ]
