# Generated by Django 3.1.9 on 2021-10-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_spell_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellsource',
            name='name',
            field=models.CharField(choices=[('phb', "Player's Handbook"), ('xge', "Xanathar's Guide to Everything"), ('tce', "Tasha's Cauldron of Everything")], max_length=255, primary_key=True, serialize=False),
        ),
    ]
