# Generated by Django 3.1.9 on 2023-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_auto_20211026_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellsource',
            name='name',
            field=models.CharField(choices=[('phb', "Player's Handbook"), ('xge', "Xanathar's Guide to Everything"), ('tce', "Tasha's Cauldron of Everything"), ('kpdm', 'Kobold Press Deep Magic')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
